//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektroikHayvanKimliklendirmeAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hayvancilikta_Elektronik_KimliklendirmeEntities : DbContext
    {
        public Hayvancilikta_Elektronik_KimliklendirmeEntities()
            : base("name=Hayvancilikta_Elektronik_KimliklendirmeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HayvanHastalik> HayvanHastalik { get; set; }
        public virtual DbSet<HayvanKimlik> HayvanKimlik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VeterinerKimlik> VeterinerKimlik { get; set; }
    }
}
