//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektroikHayvanKimliklendirmeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HayvanKimlik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HayvanKimlik()
        {
            this.HayvanHastalik = new HashSet<HayvanHastalik>();
        }
    
        public string KupeNo { get; set; }
        public string SuruNo { get; set; }
        public string Cinsi { get; set; }
        public short Yas { get; set; }
        public string AnaCinsi { get; set; }
        public string BabaCinsi { get; set; }
        public string BuzagiSayisi { get; set; }
        public string AnaKodu { get; set; }
        public byte GecirdigiHastalikSayisi { get; set; }
        public string Durum { get; set; }
        public string DogduguMemleket { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HayvanHastalik> HayvanHastalik { get; set; }
    }
}
