//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElektroikHayvanKimliklendirmeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HayvanHastalik
    {
        public int Id { get; set; }
        public string HayvanKupeNo { get; set; }
        public string HastalikIsmi { get; set; }
        public string YapilanTedavi { get; set; }
        public Nullable<int> VeterinerNo { get; set; }
    
        public virtual VeterinerKimlik VeterinerKimlik { get; set; }
        public virtual HayvanKimlik HayvanKimlik { get; set; }
    }
}
